stages:
 - Build
 - Cleanup

variables:
  build_number: "${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
  image: "registry.git.vgregion.se/${CI_PROJECT_PATH}"

default:
  tags:
  - ai
  before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

Build image:
  stage: Build
  script:
  - docker build . -t $image:$build_number
  - docker tag $image:$build_number $image:latest
  - docker push $image:$build_number
  - docker push $image:latest

Cleanup image:
  stage: Cleanup
  before_script:
  - pip3 install Utilities==0.1.0 --index-url https://git.vgregion.se/api/v4/projects/3383/packages/pypi/simple
  script:
  - |
    python -c "from utilities import ContainerRepository;
    import os; r = ContainerRepository(os.environ['CI_JOB_TOKEN']);
    r.delete_image_from_project(os.environ['CI_PROJECT_PATH']os.environ['CI_JOB_IMAGE'], os.environ['CI_PROJECT_PATH'])