site_name: {{ cookiecutter.project_name }} dokumentation
# site_url: https://site/
site_favicon: favicon.ico
# repo_url: https://git/<fill_in_group_name>/{{ cookiecutter.repo_name }}
repo_name: {{ cookiecutter.repo_name }}
docs_dir: docs
theme:
  icon:
    repo: fontawesome/brands/git-alt
  language: sv
  name: material
  palette:
    scheme: default
plugins:
  - search
  - git-revision-date
pages:
  - Home: index.md